name: Automatic Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-out:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements package
        run: |
          pip install --upgrade pip
          pip install -r ./user_info/requirements.txt

      - name: Autopep8 testing
        id: autopep8_test
        run: |
          autopep8 ./user_info/*.py

      - name: Send message when autopep8 testing succeeds
        if: steps.autopep8_test.outcome == 'success'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Passed autopep8 testing!"}' $DISCORD_WEBHOOK

      - name: Send message when autopep8 testing fails
        if: steps.autopep8_test.outcome == 'failure'
        run: |
          autopep8 ./user_info/*.py > autopep8_output.txt || true
          autopep8_output=$(cat autopep8_output.txt)
          autopep8_json='{"content":"'"$autopep8_output"'"}'
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Autopep8 testing failed! Please review and fix the identified issues."}' $DISCORD_WEBHOOK
          echo $autopep8_json | curl -X POST -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK
        continue-on-error: true
  
      - name: Pylint testing
        id: pylint_test
        run: |
          pylint ./user_info/.

      - name: Send message when pylint testing succeeds
        if: steps.pylint_test.outcome == 'success'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Passed pylint testing!"}' $DISCORD_WEBHOOK

      - name: Send message when pylint testing fails
        if: steps.pylint_test.outcome == 'failure'
        run: |
          pylint ./user_info/. > pylint_output.txt || true
          pylint_output=$(cat pylint_output.txt)
          pylint_json='{"content":"'"$pylint_output"'"}'
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Pylint testing failed! Please review and fix the identified issues."}' $DISCORD_WEBHOOK
          echo $pylint_json | curl -X POST -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK
        continue-on-error: true
