name: Automatic continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install requirements package
        run: |
          pip install --upgrade pip
          pip install -r ./user_info/requirements.txt
      - name: pep8, pylint testing
        run: |
          autopep8 ./user_info/*.py
          pylint ./user_info/*.py
      - name: Generate Environment Variables File
        run: |
          echo "DISCORD_WEBHOOK=$DISCORD_WEBHOOK" >> .env
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send build status to Discord
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Build succeeded!"}' ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send pylint output to Discord on failure
        if: failure()
        run: |
          pylint ./user_info/*.py > pylint_output.txt || true
          pylint_output=$(cat pylint_output.txt)
          json='{"content":"'"$pylint_output"'"}'
          curl -X POST -H "Content-Type: application/json" -d '{"content":"Build failed!"}' ${{ secrets.DISCORD_WEBHOOK }}
          echo $json | curl -X POST -H "Content-Type: application/json" -d @- ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true
