name: Automatic Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-out:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements package
        run: |
          pip install --upgrade pip
          pip install -r ./user_info/requirements.txt

      - name: Autopep8 testing
        run: |
          autopep8 ./user_info/*.py
          if [ $? -eq 0 ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"content":"Passed autopep8 testing!"}' $DISCORD_WEBHOOK
          else
            autopep8 ./user_info/*.py > autopep8_output.txt || true
            autopep8_output=$(cat autopep8_output.txt)
            autopep8_json='{"content":"'"$autopep8_output"'"}'
            curl -X POST -H "Content-Type: application/json" -d '{"content":"Autopep8 testing failed! Please review and fix the identified issues."}' $DISCORD_WEBHOOK
            echo $autopep8_json | curl -X POST -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK
          fi
  
      - name: Pylint testing
        run: |
          pylint ./user_info/.
          if [ $? -eq 0 ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"content":"Passed pylint testing!"}' $DISCORD_WEBHOOK
          else
            pylint ./user_info/. > pylint_output.txt || true
            pylint_output=$(cat pylint_output.txt)
            pylint_json='{"content":"'"$pylint_output"'"}'
            curl -X POST -H "Content-Type: application/json" -d '{"content":"Pylint testing failed! Please review and fix the identified issues."}' $DISCORD_WEBHOOK
            echo $pylint_json | curl -X POST -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK
          fi
